services:
  products-db:
    image: postgres:17.4
    env_file:
      - ./apps/products.microservice/.env.local
    ports:
      - 5432:5432
    volumes:
      - products-data:/var/lib/postgresql/data

  products-ms:
    image: products-microservice:1.3
    ports:
      - 3000:3000
    env_file:
      - ./apps/products.microservice/.env.local
    depends_on:
      - products-db
      - rabbitmq

  orders-db:
    image: postgres:17.4
    env_file:
      - ./apps/orders.microservice/.env.local
    ports:
      - 5433:5432
    volumes:
      - orders-data:/var/lib/postgresql/data

  orders-ms:
    image: orders-microservice:1.0
    env_file:
      - ./apps/orders.microservice/.env.local
    ports:
      - 3001:3000
    depends_on:
      - orders-db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4.1-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  products-data:
  orders-data:
  rabbitmq-data:
